aleph2:
  joints:

    gimbal1_pan:
      type: rubi_stepper
      board_name: gimbal
      board_id: "00000000"
      position_field: position_pan
      velocity_field: velocity_pan
      # home_field: home_pan
      scale: 1600.0
    gimbal1_tilt:
      type: rubi_stepper
      board_name: gimbal
      board_id: "00000000"
      position_field: position_tilt
      velocity_field: velocity_tilt
      # home_field: home_tilt
      scale: 1900.0
    gimbal1_zoom:
      type: rubi_stepper
      board_name: gimbal
      board_id: "00000000"
      position_field: position_zoom
      velocity_field: velocity_zoom
      home_field: home_zoom
      scale: 1900.0
    gimbal1_focus:
      type: rubi_stepper
      board_name: gimbal
      board_id: "00000000"
      position_field: position_focus
      velocity_field: velocity_focus
      home_field: home_focus
      scale: 1900.0

    gimbal2_pan:
      type: rubi_stepper
      board_name: gimbal
      board_id: "00000001"
      position_field: position_pan
      velocity_field: velocity_pan
      # home_field: home_pan
      scale: 1600.0
    gimbal2_tilt:
      type: rubi_stepper
      board_name: gimbal
      board_id: "00000001"
      position_field: position_tilt
      velocity_field: velocity_tilt
      # home_field: home_tilt
      scale: 1900.0
    gimbal2_zoom:
      type: rubi_stepper
      board_name: gimbal
      board_id: "00000001"
      position_field: position_zoom
      velocity_field: velocity_zoom
      home_field: home_zoom
      scale: 1900.0
    gimbal2_focus:
      type: rubi_stepper
      board_name: gimbal
      board_id: "00000001"
      position_field: position_focus
      velocity_field: velocity_focus
      home_field: home_focus
      scale: 1900.0

    gimbal3_pan:
      type: rubi_stepper
      board_name: gimbal
      board_id: "00000002"
      position_field: position_pan
      velocity_field: velocity_pan
      # home_field: home_pan
      scale: 1600.0
    gimbal3_tilt:
      type: rubi_stepper
      board_name: gimbal
      board_id: "00000002"
      position_field: position_tilt
      velocity_field: velocity_tilt
      # home_field: home_tilt
      scale: 1900.0
    gimbal3_zoom:
      type: rubi_stepper
      board_name: gimbal
      board_id: "00000002"
      position_field: position_zoom
      velocity_field: velocity_zoom
      home_field: home_zoom
      scale: 1900.0
    gimbal3_focus:
      type: rubi_stepper
      board_name: gimbal
      board_id: "00000002"
      position_field: position_focus
      velocity_field: velocity_focus
      home_field: home_focus
      scale: 1900.0

    gimbal4_pan:
      type: rubi_stepper
      board_name: gimbal
      board_id: "00000003"
      position_field: position_pan
      velocity_field: velocity_pan
      # home_field: home_pan
      scale: 1600.0
    gimbal4_tilt:
      type: rubi_stepper
      board_name: gimbal
      board_id: "00000003"
      position_field: position_tilt
      velocity_field: velocity_tilt
      # home_field: home_tilt
      scale: 1900.0
    gimbal4_zoom:
      type: rubi_stepper
      board_name: gimbal
      board_id: "00000003"
      position_field: position_zoom
      velocity_field: velocity_zoom
      home_field: home_zoom
      scale: 1900.0
    gimbal4_focus:
      type: rubi_stepper
      board_name: gimbal
      board_id: "00000003"
      position_field: position_focus
      velocity_field: velocity_focus
      home_field: home_focus
      scale: 1900.0