joint_limits:
  manip_base_joint:
    has_position_limits: false
    has_velocity_limits: false
    has_acceleration_limits: false
    has_jerk_limits: false
    has_effort_limits: false
    has_soft_limits: false
  manip_shoulder_joint:
    has_position_limits: false
    has_velocity_limits: false
    has_acceleration_limits: false
    has_jerk_limits: false
    has_effort_limits: false
    has_soft_limits: false
  manip_elbow_joint:
    has_position_limits: false
    has_velocity_limits: false
    has_acceleration_limits: false
    has_jerk_limits: false
    has_effort_limits: false
    has_soft_limits: false
  manip_wrist_tilt_joint:
    has_position_limits: false
    has_velocity_limits: false
    has_acceleration_limits: false
    has_jerk_limits: false
    has_effort_limits: false
    has_soft_limits: false
  manip_wrist_roll_joint:
    has_position_limits: false
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    has_jerk_limits: false
    has_effort_limits: true
    max_effort: 500
    has_soft_limits: false
  manip_gripper_joint:
    has_position_limits: false
    has_velocity_limits: true
    max_velocity: 10.0
    has_acceleration_limits: false
    has_jerk_limits: false
    has_effort_limits: true
    max_effort: 500
    has_soft_limits: false