options:
  dcf_path: "@BUS_CONFIG_PATH@"

master:
  node_id: 100
  driver: "ros2_canopen::MasterDriver"
  package: canopen_master_driver
  sync_period: 20000
  heartbeat_producer: 100
  start_nodes: false
  reset_all_nodes: true

nanotec1:
  node_id: 1
  dcf: "C5-E-2-09.eds"
  driver: "nanotec_driver::NanotecDriver"
  package: "nanotec_driver"
  period: 20
  boot: true
  heartbeat_consumer: true
  enable_lazy_load: false
  sdo:
    - { index: 0x2030, sub_index: 0, value: 8 } # Pole Pair Count
    - { index: 0x2031, sub_index: 0, value: 12000 } # Max Motor Current - 12 A
    - { index: 0x203B, sub_index: 1, value: 10000 } # Motor Rated Current - 12 A
    - { index: 0x203B, sub_index: 2, value: 100 } # Maximum Duration Of Max Current - 100ms
    - { index: 0x6072, sub_index: 0, value: 1200 } # Max Torque - 120% of rated torque
    - { index: 0x6073, sub_index: 0, value: 1200 } # Max Current - 100% of rated current
    - { index: 0x6087, sub_index: 0, value: 1000 } # Torque Slope - 100% of rated torque per second
    - { index: 0x3202, sub_index: 0, value: 0x41 } # Motor Drive Submode Select - BLDC motor (closed loop)
    - { index: 0x3212, sub_index: 4, value: 1 } # Use new motor drive parameters
    - { index: 0x321A, sub_index: 1, value: 100 } # Current Controller - Proportional Gain Kp For Iq [mV/A]
    - { index: 0x321A, sub_index: 2, value: 2000 } # Current Controller - Integrator Time Ti For Iq [μs]
    - { index: 0x321A, sub_index: 3, value: 100 } # Current Controller - Proportional Gain Kp For Id [mV/A]
    - { index: 0x321A, sub_index: 4, value: 2000 } # Current Controller - Integrator Time Ti For Id [μs]
    - { index: 0x321B, sub_index: 1, value: 384 } # Velocity Controller - Proportiona Gain Kp [mA/Hz]
    - { index: 0x321B, sub_index: 2, value: 34464 } # Velocty Controller - Integrator Time Ti [μs]
    - { index: 0x6083, sub_index: 0, value: 30000 } # Profile Acceleration
    - { index: 0x6084, sub_index: 0, value: 60000 } # Profile Deceleration
    - { index: 0x60C5, sub_index: 0, value: 35000 } # Max Acceleration
    - { index: 0x60C6, sub_index: 0, value: 70000 } # Max Deceleration
    - { index: 0x607F, sub_index: 0, value: 50000 } # Max Profile Velocity
    - { index: 0x6080, sub_index: 0, value: 55000 } # Max Motor speed
    - { index: 0x60A8, sub_index: 0, value: 0xFD100000 } # SI Unit Position - rad, factor 1e-3
    - { index: 0x60A9, sub_index: 0, value: 0xFD100300 } # SI Unit Velocity - rad/s, factor 1e-3
    - { index: 0x6091, sub_index: 1, value: 12 } # Gear ratio - 12:1
  tpdo:
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - { index: 0x6041, sub_index: 0 } # status word
        - { index: 0x6061, sub_index: 0 } # mode of operaiton display
        - { index: 0x6077, sub_index: 0 } # Torque Actual Value
    2:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - { index: 0x6064, sub_index: 0 } # position actual value
        - { index: 0x606c, sub_index: 0 } # velocity actual position
  rpdo:
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - { index: 0x6040, sub_index: 0 } # controlword
        - { index: 0x6060, sub_index: 0 } # mode of operation
    2:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - { index: 0x607A, sub_index: 0 } # target position
        - { index: 0x60FF, sub_index: 0 } # target velocity

nanotec2:
  node_id: 2
  dcf: "C5-E-2-09.eds"
  driver: "nanotec_driver::NanotecDriver"
  package: "nanotec_driver"
  period: 20
  boot: true
  heartbeat_consumer: true
  enable_lazy_load: false
  sdo:
    - { index: 0x2030, sub_index: 0, value: 8 } # Pole Pair Count
    - { index: 0x2031, sub_index: 0, value: 12000 } # Max Motor Current - 12 A
    - { index: 0x203B, sub_index: 1, value: 10000 } # Motor Rated Current - 12 A
    - { index: 0x203B, sub_index: 2, value: 100 } # Maximum Duration Of Max Current - 100ms
    - { index: 0x6072, sub_index: 0, value: 1200 } # Max Torque - 120% of rated torque
    - { index: 0x6073, sub_index: 0, value: 1200 } # Max Current - 100% of rated current
    - { index: 0x6087, sub_index: 0, value: 1000 } # Torque Slope - 100% of rated torque per second
    - { index: 0x3202, sub_index: 0, value: 0x41 } # Motor Drive Submode Select - BLDC motor (closed loop)
    - { index: 0x3212, sub_index: 4, value: 1 } # Use new motor drive parameters
    - { index: 0x321A, sub_index: 1, value: 100 } # Current Controller - Proportional Gain Kp For Iq [mV/A]
    - { index: 0x321A, sub_index: 2, value: 2000 } # Current Controller - Integrator Time Ti For Iq [μs]
    - { index: 0x321A, sub_index: 3, value: 100 } # Current Controller - Proportional Gain Kp For Id [mV/A]
    - { index: 0x321A, sub_index: 4, value: 2000 } # Current Controller - Integrator Time Ti For Id [μs]
    - { index: 0x321B, sub_index: 1, value: 384 } # Velocity Controller - Proportiona Gain Kp [mA/Hz]
    - { index: 0x321B, sub_index: 2, value: 34464 } # Velocty Controller - Integrator Time Ti [μs]
    - { index: 0x6083, sub_index: 0, value: 30000 } # Profile Acceleration
    - { index: 0x6084, sub_index: 0, value: 60000 } # Profile Deceleration
    - { index: 0x60C5, sub_index: 0, value: 35000 } # Max Acceleration
    - { index: 0x60C6, sub_index: 0, value: 70000 } # Max Deceleration
    - { index: 0x607F, sub_index: 0, value: 50000 } # Max Profile Velocity
    - { index: 0x6080, sub_index: 0, value: 55000 } # Max Motor speed
    - { index: 0x60A8, sub_index: 0, value: 0xFD100000 } # SI Unit Position - rad, factor 1e-3
    - { index: 0x60A9, sub_index: 0, value: 0xFD100300 } # SI Unit Velocity - rad/s, factor 1e-3
    - { index: 0x6091, sub_index: 1, value: 12 } # Gear ratio - 12:1
  tpdo:
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - { index: 0x6041, sub_index: 0 } # status word
        - { index: 0x6061, sub_index: 0 } # mode of operaiton display
        - { index: 0x6077, sub_index: 0 } # Torque Actual Value
    2:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - { index: 0x6064, sub_index: 0 } # position actual value
        - { index: 0x606c, sub_index: 0 } # velocity actual position
  rpdo:
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - { index: 0x6040, sub_index: 0 } # controlword
        - { index: 0x6060, sub_index: 0 } # mode of operation
    2:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - { index: 0x607A, sub_index: 0 } # target position
        - { index: 0x60FF, sub_index: 0 } # target velocity

nanotec3:
  node_id: 3
  dcf: "C5-E-2-09.eds"
  driver: "nanotec_driver::NanotecDriver"
  package: "nanotec_driver"
  period: 20
  boot: true
  heartbeat_consumer: true
  enable_lazy_load: false
  sdo:
    - { index: 0x2030, sub_index: 0, value: 8 } # Pole Pair Count
    - { index: 0x2031, sub_index: 0, value: 12000 } # Max Motor Current - 12 A
    - { index: 0x203B, sub_index: 1, value: 10000 } # Motor Rated Current - 12 A
    - { index: 0x203B, sub_index: 2, value: 100 } # Maximum Duration Of Max Current - 100ms
    - { index: 0x6072, sub_index: 0, value: 1200 } # Max Torque - 120% of rated torque
    - { index: 0x6073, sub_index: 0, value: 1200 } # Max Current - 100% of rated current
    - { index: 0x6087, sub_index: 0, value: 1000 } # Torque Slope - 100% of rated torque per second
    - { index: 0x3202, sub_index: 0, value: 0x41 } # Motor Drive Submode Select - BLDC motor (closed loop)
    - { index: 0x3212, sub_index: 4, value: 1 } # Use new motor drive parameters
    - { index: 0x321A, sub_index: 1, value: 100 } # Current Controller - Proportional Gain Kp For Iq [mV/A]
    - { index: 0x321A, sub_index: 2, value: 2000 } # Current Controller - Integrator Time Ti For Iq [μs]
    - { index: 0x321A, sub_index: 3, value: 100 } # Current Controller - Proportional Gain Kp For Id [mV/A]
    - { index: 0x321A, sub_index: 4, value: 2000 } # Current Controller - Integrator Time Ti For Id [μs]
    - { index: 0x321B, sub_index: 1, value: 384 } # Velocity Controller - Proportiona Gain Kp [mA/Hz]
    - { index: 0x321B, sub_index: 2, value: 34464 } # Velocty Controller - Integrator Time Ti [μs]
    - { index: 0x6083, sub_index: 0, value: 30000 } # Profile Acceleration
    - { index: 0x6084, sub_index: 0, value: 60000 } # Profile Deceleration
    - { index: 0x60C5, sub_index: 0, value: 35000 } # Max Acceleration
    - { index: 0x60C6, sub_index: 0, value: 70000 } # Max Deceleration
    - { index: 0x607F, sub_index: 0, value: 50000 } # Max Profile Velocity
    - { index: 0x6080, sub_index: 0, value: 55000 } # Max Motor speed
    - { index: 0x60A8, sub_index: 0, value: 0xFD100000 } # SI Unit Position - rad, factor 1e-3
    - { index: 0x60A9, sub_index: 0, value: 0xFD100300 } # SI Unit Velocity - rad/s, factor 1e-3
    - { index: 0x6091, sub_index: 1, value: 12 } # Gear ratio - 12:1
    - { index: 0x607E, sub_index: 0, value: 0b11000000 } # Polarity - Reversed
  tpdo:
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - { index: 0x6041, sub_index: 0 } # status word
        - { index: 0x6061, sub_index: 0 } # mode of operaiton display
        - { index: 0x6077, sub_index: 0 } # Torque Actual Value
    2:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - { index: 0x6064, sub_index: 0 } # position actual value
        - { index: 0x606c, sub_index: 0 } # velocity actual position
  rpdo:
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - { index: 0x6040, sub_index: 0 } # controlword
        - { index: 0x6060, sub_index: 0 } # mode of operation
    2:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - { index: 0x607A, sub_index: 0 } # target position
        - { index: 0x60FF, sub_index: 0 } # target velocity

nanotec4:
  node_id: 4
  dcf: "C5-E-2-09.eds"
  driver: "nanotec_driver::NanotecDriver"
  package: "nanotec_driver"
  period: 20
  boot: true
  heartbeat_consumer: true
  enable_lazy_load: false
  sdo:
    - { index: 0x2030, sub_index: 0, value: 8 } # Pole Pair Count
    - { index: 0x2031, sub_index: 0, value: 12000 } # Max Motor Current - 12 A
    - { index: 0x203B, sub_index: 1, value: 10000 } # Motor Rated Current - 12 A
    - { index: 0x203B, sub_index: 2, value: 100 } # Maximum Duration Of Max Current - 100ms
    - { index: 0x6072, sub_index: 0, value: 1200 } # Max Torque - 120% of rated torque
    - { index: 0x6073, sub_index: 0, value: 1200 } # Max Current - 100% of rated current
    - { index: 0x6087, sub_index: 0, value: 1000 } # Torque Slope - 100% of rated torque per second
    - { index: 0x3202, sub_index: 0, value: 0x41 } # Motor Drive Submode Select - BLDC motor (closed loop)
    - { index: 0x3212, sub_index: 4, value: 1 } # Use new motor drive parameters
    - { index: 0x321A, sub_index: 1, value: 100 } # Current Controller - Proportional Gain Kp For Iq [mV/A]
    - { index: 0x321A, sub_index: 2, value: 2000 } # Current Controller - Integrator Time Ti For Iq [μs]
    - { index: 0x321A, sub_index: 3, value: 100 } # Current Controller - Proportional Gain Kp For Id [mV/A]
    - { index: 0x321A, sub_index: 4, value: 2000 } # Current Controller - Integrator Time Ti For Id [μs]
    - { index: 0x321B, sub_index: 1, value: 384 } # Velocity Controller - Proportiona Gain Kp [mA/Hz]
    - { index: 0x321B, sub_index: 2, value: 34464 } # Velocty Controller - Integrator Time Ti [μs]
    - { index: 0x6083, sub_index: 0, value: 30000 } # Profile Acceleration
    - { index: 0x6084, sub_index: 0, value: 60000 } # Profile Deceleration
    - { index: 0x60C5, sub_index: 0, value: 35000 } # Max Acceleration
    - { index: 0x60C6, sub_index: 0, value: 70000 } # Max Deceleration
    - { index: 0x607F, sub_index: 0, value: 50000 } # Max Profile Velocity
    - { index: 0x6080, sub_index: 0, value: 55000 } # Max Motor speed
    - { index: 0x60A8, sub_index: 0, value: 0xFD100000 } # SI Unit Position - rad, factor 1e-3
    - { index: 0x60A9, sub_index: 0, value: 0xFD100300 } # SI Unit Velocity - rad/s, factor 1e-3
    - { index: 0x6091, sub_index: 1, value: 12 } # Gear ratio - 12:1
    - { index: 0x607E, sub_index: 0, value: 0b11000000 } # Polarity - Reversed
  tpdo:
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - { index: 0x6041, sub_index: 0 } # status word
        - { index: 0x6061, sub_index: 0 } # mode of operaiton display
        - { index: 0x6077, sub_index: 0 } # Torque Actual Value
    2:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - { index: 0x6064, sub_index: 0 } # position actual value
        - { index: 0x606c, sub_index: 0 } # velocity actual position
  rpdo:
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - { index: 0x6040, sub_index: 0 } # controlword
        - { index: 0x6060, sub_index: 0 } # mode of operation
    2:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - { index: 0x607A, sub_index: 0 } # target position
        - { index: 0x60FF, sub_index: 0 } # target velocity
