rosbags:
  control:
    - "/rosout_agg"
    - "/tf"
    - "/tf_static"
    - "/aleph2/joint_states"
    - "/aleph2/drivetrain_control_loop/usage"
    - "/aleph2/drivetrain/controllers/diff_drive/cmd_vel"
    - "/aleph2/drivetrain/controllers/diff_drive/odom"
    - "/aleph2/drivetrain/controllers/diff_drive/parameter_descriptions"
    - "/aleph2/drivetrain/controllers/diff_drive/parameter_updates"
    - "/aleph2/drivetrain/joints/wheel_FL_joint/parameter_descriptions"
    - "/aleph2/drivetrain/joints/wheel_FL_joint/parameter_updates"
    - "/aleph2/drivetrain/joints/wheel_FR_joint/parameter_descriptions"
    - "/aleph2/drivetrain/joints/wheel_FR_joint/parameter_updates"
    - "/aleph2/drivetrain/joints/wheel_RL_joint/parameter_descriptions"
    - "/aleph2/drivetrain/joints/wheel_RL_joint/parameter_updates"
    - "/aleph2/drivetrain/joints/wheel_RR_joint/parameter_descriptions"
    - "/aleph2/drivetrain/joints/wheel_RR_joint/parameter_updates"
    - "/aleph2/gimbal_control_loop/usage"
    - "/aleph2/gimbal/controllers/velocity/gimbal1_focus/command"
    - "/aleph2/gimbal/controllers/velocity/gimbal1_pan/command"
    - "/aleph2/gimbal/controllers/velocity/gimbal1_tilt/command"
    - "/aleph2/gimbal/controllers/velocity/gimbal1_zoom/command"
    - "/aleph2/gimbal/controllers/velocity/gimbal2_focus/command"
    - "/aleph2/gimbal/controllers/velocity/gimbal2_pan/command"
    - "/aleph2/gimbal/controllers/velocity/gimbal2_tilt/command"
    - "/aleph2/gimbal/controllers/velocity/gimbal2_zoom/command"
    - "/aleph2/gimbal/controllers/velocity/gimbal3_focus/command"
    - "/aleph2/gimbal/controllers/velocity/gimbal3_pan/command"
    - "/aleph2/gimbal/controllers/velocity/gimbal3_tilt/command"
    - "/aleph2/gimbal/controllers/velocity/gimbal3_zoom/command"
    - "/aleph2/gimbal/controllers/velocity/gimbal4_focus/command"
    - "/aleph2/gimbal/controllers/velocity/gimbal4_pan/command"
    - "/aleph2/gimbal/controllers/velocity/gimbal4_tilt/command"
    - "/aleph2/gimbal/controllers/velocity/gimbal4_zoom/command"
    - "/aleph2/manip_control_loop/usage"
    - "/aleph2/manip/controllers/effort/base/command"
    - "/aleph2/manip/controllers/effort/elbow/command"
    - "/aleph2/manip/controllers/effort/gripper/command"
    - "/aleph2/manip/controllers/effort/shoulder/command"
    - "/aleph2/manip/controllers/effort/wrist_roll/command"
    - "/aleph2/manip/controllers/effort/wrist_tilt/command"
    - "/aleph2/manip/controllers/velocity/base/command"
    - "/aleph2/manip/controllers/velocity/base/pid/parameter_descriptions"
    - "/aleph2/manip/controllers/velocity/base/pid/parameter_updates"
    - "/aleph2/manip/controllers/velocity/base/state"
    - "/aleph2/manip/controllers/velocity/elbow/command"
    - "/aleph2/manip/controllers/velocity/elbow/pid/parameter_descriptions"
    - "/aleph2/manip/controllers/velocity/elbow/pid/parameter_updates"
    - "/aleph2/manip/controllers/velocity/elbow/state"
    - "/aleph2/manip/controllers/velocity/gripper/command"
    - "/aleph2/manip/controllers/velocity/gripper/pid/parameter_descriptions"
    - "/aleph2/manip/controllers/velocity/gripper/pid/parameter_updates"
    - "/aleph2/manip/controllers/velocity/gripper/state"
    - "/aleph2/manip/controllers/velocity/shoulder/command"
    - "/aleph2/manip/controllers/velocity/shoulder/pid/parameter_descriptions"
    - "/aleph2/manip/controllers/velocity/shoulder/pid/parameter_updates"
    - "/aleph2/manip/controllers/velocity/shoulder/state"
    - "/aleph2/manip/controllers/velocity/wrist_roll/command"
    - "/aleph2/manip/controllers/velocity/wrist_roll/pid/parameter_descriptions"
    - "/aleph2/manip/controllers/velocity/wrist_roll/pid/parameter_updates"
    - "/aleph2/manip/controllers/velocity/wrist_roll/state"
    - "/aleph2/manip/controllers/velocity/wrist_tilt/command"
    - "/aleph2/manip/controllers/velocity/wrist_tilt/pid/parameter_descriptions"
    - "/aleph2/manip/controllers/velocity/wrist_tilt/pid/parameter_updates"
    - "/aleph2/manip/controllers/velocity/wrist_tilt/state"
    - "/aleph2/manip/controllers/position/base/command"
    - "/aleph2/manip/controllers/position/base/pid/parameter_descriptions"
    - "/aleph2/manip/controllers/position/base/pid/parameter_updates"
    - "/aleph2/manip/controllers/position/base/state"
    - "/aleph2/manip/controllers/position/elbow/command"
    - "/aleph2/manip/controllers/position/elbow/pid/parameter_descriptions"
    - "/aleph2/manip/controllers/position/elbow/pid/parameter_updates"
    - "/aleph2/manip/controllers/position/elbow/state"
    - "/aleph2/manip/controllers/position/gripper/command"
    - "/aleph2/manip/controllers/position/gripper/pid/parameter_descriptions"
    - "/aleph2/manip/controllers/position/gripper/pid/parameter_updates"
    - "/aleph2/manip/controllers/position/gripper/state"
    - "/aleph2/manip/controllers/position/shoulder/command"
    - "/aleph2/manip/controllers/position/shoulder/pid/parameter_descriptions"
    - "/aleph2/manip/controllers/position/shoulder/pid/parameter_updates"
    - "/aleph2/manip/controllers/position/shoulder/state"
    - "/aleph2/manip/controllers/position/wrist_roll/command"
    - "/aleph2/manip/controllers/position/wrist_roll/pid/parameter_descriptions"
    - "/aleph2/manip/controllers/position/wrist_roll/pid/parameter_updates"
    - "/aleph2/manip/controllers/position/wrist_roll/state"
    - "/aleph2/manip/controllers/position/wrist_tilt/command"
    - "/aleph2/manip/controllers/position/wrist_tilt/pid/parameter_descriptions"
    - "/aleph2/manip/controllers/position/wrist_tilt/pid/parameter_updates"
    - "/aleph2/manip/controllers/position/wrist_tilt/state"
    - "/aleph2/manip/controllers/trajectory/command"
    - "/aleph2/manip/controllers/trajectory/follow_joint_trajectory/cancel"
    - "/aleph2/manip/controllers/trajectory/follow_joint_trajectory/feedback"
    - "/aleph2/manip/controllers/trajectory/follow_joint_trajectory/goal"
    - "/aleph2/manip/controllers/trajectory/follow_joint_trajectory/result"
    - "/aleph2/manip/controllers/trajectory/follow_joint_trajectory/status"
    - "/aleph2/manip/controllers/trajectory/gains/manip_base_joint/parameter_descriptions"
    - "/aleph2/manip/controllers/trajectory/gains/manip_base_joint/parameter_updates"
    - "/aleph2/manip/controllers/trajectory/gains/manip_elbow_joint/parameter_descriptions"
    - "/aleph2/manip/controllers/trajectory/gains/manip_elbow_joint/parameter_updates"
    - "/aleph2/manip/controllers/trajectory/gains/manip_gripper_joint/parameter_descriptions"
    - "/aleph2/manip/controllers/trajectory/gains/manip_gripper_joint/parameter_updates"
    - "/aleph2/manip/controllers/trajectory/gains/manip_shoulder_joint/parameter_descriptions"
    - "/aleph2/manip/controllers/trajectory/gains/manip_shoulder_joint/parameter_updates"
    - "/aleph2/manip/controllers/trajectory/gains/manip_wrist_roll_joint/parameter_descriptions"
    - "/aleph2/manip/controllers/trajectory/gains/manip_wrist_roll_joint/parameter_updates"
    - "/aleph2/manip/controllers/trajectory/gains/manip_wrist_tilt_joint/parameter_descriptions"
    - "/aleph2/manip/controllers/trajectory/gains/manip_wrist_tilt_joint/parameter_updates"
    - "/aleph2/manip/controllers/trajectory/state"
    - "/power_status"
  sensors:
    - "sensor1"
    - "sensor2"
  cameras:
    - "camera1"
    - "camera2"