aleph2:
  joint:
    kolo_RL_to_chromosom_L:
      type: "nanotec"
      node_id: 1
      busname: "can0"
      baudrate: "500K"
      scale: 1000.0
      parameters:
        Maximum current: 25000
        I2t Parameters:
          Nominal Current: 25000
          Maximum duration of peak current: 100
        Profile velocity: 20000
        Profile acceleration: 10000
        Profile deceleration: 10000
        Max acceleration: 15000
        Max develeration: 15000
        Max torque: 1000
        Torque slope: 1000
        Motor drive parameter set:
          Flux current loop, integral gain (closed loop): 256
          Flux current loop, proportional gain (closed loop): 8192
          Position loop, integral gain (closed loop): 0
          Position loop, proportional gain (closed loop): 2048
          Torque current loop, integral gain (closed loop): 256
          Torque current loop, integral gain (open loop): 45000
          Torque current loop, proportional gain (closed loop): 8192
          Torque current loop, proportional gain (open loop): 240000
          Velocity loop, integral gain (closed loop): 5
          Velocity loop, proportional gain (closed loop): 30000
        Position encoder resolution:
          Encoder increments: 6280 # 2 * pi * scale
          Motor revolutions: 1
        Gear ratio:
          Motor revolutions: 12
          Shaft revolutions: 1 
        Velocity numerator: 1
        Velocity denominator: 524 # (2 * pi * scale) / (Gear ratio)
        Pole pair count: 8
    kolo_RR_to_chromosom_R:
      type: "nanotec"
      node_id: 2
      busname: "can0"
      baudrate: "500K"
      scale: -1000.0
      parameters:
        Maximum current: 25000
        I2t Parameters:
          Nominal Current: 25000
          Maximum duration of peak current: 100
        Profile velocity: 20000
        Profile acceleration: 10000
        Profile deceleration: 10000
        Max acceleration: 15000
        Max develeration: 15000
        Max torque: 1000
        Torque slope: 1000
        Motor drive parameter set:
          Flux current loop, integral gain (closed loop): 256
          Flux current loop, proportional gain (closed loop): 8192
          Position loop, integral gain (closed loop): 0
          Position loop, proportional gain (closed loop): 2048
          Torque current loop, integral gain (closed loop): 256
          Torque current loop, integral gain (open loop): 45000
          Torque current loop, proportional gain (closed loop): 8192
          Torque current loop, proportional gain (open loop): 240000
          Velocity loop, integral gain (closed loop): 5
          Velocity loop, proportional gain (closed loop): 30000
        Position encoder resolution:
          Encoder increments: 6280 # 2 * pi * scale
          Motor revolutions: 1
        Gear ratio:
          Motor revolutions: 12
          Shaft revolutions: 1 
        Velocity numerator: 1
        Velocity denominator: 524 # (2 * pi * scale) / (Gear ratio)
        Pole pair count: 8
    kolo_FL_to_chromosom_L:
      type: "nanotec"
      node_id: 3
      busname: "can0"
      baudrate: "500K"
      scale: 1000.0
      parameters:
        Maximum current: 25000
        I2t Parameters:
          Nominal Current: 25000
          Maximum duration of peak current: 100
        Profile velocity: 20000
        Profile acceleration: 10000
        Profile deceleration: 10000
        Max acceleration: 15000
        Max develeration: 15000
        Max torque: 1000
        Torque slope: 1000
        Motor drive parameter set:
          Flux current loop, integral gain (closed loop): 256
          Flux current loop, proportional gain (closed loop): 8192
          Position loop, integral gain (closed loop): 0
          Position loop, proportional gain (closed loop): 2048
          Torque current loop, integral gain (closed loop): 256
          Torque current loop, integral gain (open loop): 45000
          Torque current loop, proportional gain (closed loop): 8192
          Torque current loop, proportional gain (open loop): 240000
          Velocity loop, integral gain (closed loop): 5
          Velocity loop, proportional gain (closed loop): 30000
        Position encoder resolution:
          Encoder increments: 6280 # 2 * pi * scale
          Motor revolutions: 1
        Gear ratio:
          Motor revolutions: 12
          Shaft revolutions: 1 
        Velocity numerator: 1
        Velocity denominator: 524 # (2 * pi * scale) / (Gear ratio)
        Pole pair count: 8
    kolo_FR_to_chromosom_R:
      type: "nanotec"
      node_id: 4
      busname: "can0"
      baudrate: "500K"
      scale: -1000.0
      parameters:
        Maximum current: 25000
        I2t Parameters:
          Nominal Current: 25000
          Maximum duration of peak current: 100
        Profile velocity: 20000
        Profile acceleration: 10000
        Profile deceleration: 10000
        Max acceleration: 15000
        Max develeration: 15000
        Max torque: 1000
        Torque slope: 1000
        Motor drive parameter set:
          Flux current loop, integral gain (closed loop): 256
          Flux current loop, proportional gain (closed loop): 8192
          Position loop, integral gain (closed loop): 0
          Position loop, proportional gain (closed loop): 2048
          Torque current loop, integral gain (closed loop): 256
          Torque current loop, integral gain (open loop): 45000
          Torque current loop, proportional gain (closed loop): 8192
          Torque current loop, proportional gain (open loop): 240000
          Velocity loop, integral gain (closed loop): 5
          Velocity loop, proportional gain (closed loop): 30000
        Position encoder resolution:
          Encoder increments: 6280 # 2 * pi * scale
          Motor revolutions: 1
        Gear ratio:
          Motor revolutions: 12
          Shaft revolutions: 1 
        Velocity numerator: 1
        Velocity denominator: 524 # (2 * pi * scale) / (Gear ratio)
        Pole pair count: 8
