#!/usr/bin/env python

import rospy

from std_msgs.msg import Int32

rospy.init_node("gimbal_sim")

pan_position = 0
pan_velocity = 0

def velocity_callback(vel):
    global pan_velocity
    pan_velocity = vel.data

vel_sub = rospy.Subscriber(
    "rubi/gimbal1/pan_velocity",
    Int32,
    velocity_callback,
    queue_size=1
)

pos_pub = rospy.Publisher(
    "rubi/gimbal1/current_pan_position",
    Int32,
    queue_size=5
)

rate = rospy.Rate(20)
while not rospy.is_shutdown():
    pan_position += pan_velocity
    pos_pub.publish(Int32(pan_position))
    rate.sleep()