#!/usr/bin/env python

import rospy
from sensor_msgs.msg import JointState

def callback(data):
    pub.publish(data)

rospy.init_node('joint_state_republisher')

try:
    source_topic = rospy.get_param("~source_topic")
except KeyError:
    rospy.logerr("No source topic given!")
else:
    pub = rospy.Publisher("joint_states", JointState, queue_size=5)
    rospy.Subscriber(source_topic, JointState, callback, queue_size=5)

    rospy.spin()