controllers:
  effort:
    base_to_frame:
      type: effort_controllers/JointEffortController
      joint: base_to_frame
    B_to_base:
      type: effort_controllers/JointEffortController
      joint: B_to_base
    C_to_B:
      type: effort_controllers/JointEffortController
      joint: C_to_B
    effector_to_C:
      type: effort_controllers/JointEffortController
      joint: effector_to_C
    effector_roll:
      type: effort_controllers/JointEffortController
      joint: effector_roll
    effector_grip:
      type: effort_controllers/JointEffortController
      joint: effector_grip
  velocity:
    effector_roll:
      type: effort_controllers/JointVelocityController
      joint: effector_roll
      pid: {p: 50.0, i: 10.0, d: 0.0}
  state:
    type: joint_state_controller/JointStateController
    publish_rate: 20