aleph2:
  joint_limits:
    effector_roll:
      has_position_limits: true
      min_position: -100000
      max_position: 100000
      has_velocity_limits: true
      max_velocity: 10.0
      has_acceleration_limits: false
      has_jerk_limits: false
      has_effort_limits: true
      max_effort: 500
      has_soft_limits: false