vaccum:
  joint_limits:
    vaccum_rotator:
      has_position_limits: true
      min_position: 0.0
      max_position: 7.0
      has_velocity_limits: true
      max_velocity: 100
      has_acceleration_limits: false
      has_jerk_limits: false
      has_effort_limits: true
      max_effort: 1000
      has_soft_limits: false