joint_limits:
  wheel_RL_joint:
    has_position_limits: false
    min_position: -100.0
    max_position: 100.0
    has_velocity_limits: true
    max_velocity: 1000.0
    has_acceleration_limits: false
    has_jerk_limits: false
    has_effort_limits: false
    has_soft_limits: true
    soft_lower_limit: -99.0
    soft_upper_limit: 99.0
    k_position: 0.1
    k_velocity: 10.0
  wheel_RR_joint:
    has_position_limits: false
    min_position: -100.0
    max_position: 100.0
    has_velocity_limits: true
    max_velocity: 1000.0
    has_acceleration_limits: false
    has_jerk_limits: false
    has_effort_limits: false
    has_soft_limits: true
    soft_lower_limit: -99.0
    soft_upper_limit: 99.0
    k_position: 0.1
    k_velocity: 10.0
  wheel_FL_joint:
    has_position_limits: false
    min_position: -100.0
    max_position: 100.0
    has_velocity_limits: true
    max_velocity: 1000.0
    has_acceleration_limits: false
    has_jerk_limits: false
    has_effort_limits: false
    has_soft_limits: true
    soft_lower_limit: -99.0
    soft_upper_limit: 99.0
    k_position: 0.1
    k_velocity: 10.0
  wheel_FR_joint:
    has_position_limits: false
    min_position: -100.0
    max_position: 100.0
    has_velocity_limits: true
    max_velocity: 1000.0
    has_acceleration_limits: false
    has_jerk_limits: false
    has_effort_limits: false
    has_soft_limits: true
    soft_lower_limit: -99.0
    soft_upper_limit: 99.0
    k_position: 0.1
    k_velocity: 10.0