aleph2:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    velocity:
      gimbal1_pan:
        type: velocity_controllers/JointVelocityController
        joint: gimbal1_pan
      gimbal1_tilt:
        type: velocity_controllers/JointVelocityController
        joint: gimbal1_tilt
      gimbal1_zoom:
        type: velocity_controllers/JointVelocityController
        joint: gimbal1_zoom
      gimbal1_focus:
        type: velocity_controllers/JointVelocityController
        joint: gimbal1_focus