options:
  dcf_path: "@BUS_CONFIG_PATH@"

master:
  node_id: 100
  driver: "ros2_canopen::MasterDriver"
  package: canopen_master_driver
  sync_period: 20000
  heartbeat_producer: 100

nanotec11:
  node_id: 11
  dcf: "CL3-E-2-0F.eds"
  driver: "nanotec_driver::NanotecDriver"
  package: "nanotec_driver"
  period: 20
  boot: true
  heartbeat_consumer: true
  enable_lazy_load: false
  sdo:
    - { index: 0x2030, sub_index: 0, value: 1 } # Pole Pair Count
    - { index: 0x2031, sub_index: 0, value: 3000 } # Max Motor Current - 3 A
    - { index: 0x203B, sub_index: 1, value: 2000 } # Motor Rated Current - 2 A
    - { index: 0x203B, sub_index: 2, value: 100 } # Maximum Duration Of Max Current - 100ms
    - { index: 0x6072, sub_index: 0, value: 1200 } # Max Torque - 120% of rated torque
    - { index: 0x6073, sub_index: 0, value: 1200 } # Max Current - 120% of rated current
    - { index: 0x3202, sub_index: 0, value: 0x41 } # Motor Drive Submode Select - BLDC motor (closed loop)
    - { index: 0x3212, sub_index: 4, value: 1 } # Use new motor drive parameters
    - { index: 0x321A, sub_index: 1, value: 100 } # Proportional Gain Kp For Iq [mV/A]
    - { index: 0x321A, sub_index: 2, value: 0 } # Integrator Time Ti For Iq [μs]
    - { index: 0x321A, sub_index: 3, value: 100 } # Proportional Gain Kp For Id [mV/A]
    - { index: 0x321A, sub_index: 4, value: 0 } # Integrator Time Ti For Id [μs]
    - { index: 0x6083, sub_index: 0, value: 10000 } # Profile Acceleration
    - { index: 0x6084, sub_index: 0, value: 10000 } # Profile Deceleration
    - { index: 0x60A8, sub_index: 0, value: 0xFD100000 } # SI Unit Position - rad, factor 1e-3
    - { index: 0x60A9, sub_index: 0, value: 0xFD100300 } # SI Unit Velocity - rad/s, factor 1e-3
    - { index: 0x6091, sub_index: 1, value: 2044 } # Gear ratio - 204.4/1
    - { index: 0x6091, sub_index: 2, value: 10 } 
  tpdo:
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - { index: 0x6041, sub_index: 0 } # status word
        - { index: 0x6061, sub_index: 0 } # mode of operation display
        - { index: 0x6077, sub_index: 0 } # torque actual value
    2:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - { index: 0x6064, sub_index: 0 } # position actual value
        - { index: 0x606c, sub_index: 0 } # velocity actual value
  rpdo:
    1:
      enabled: true
      cob_id: "auto"
      mapping:
        - { index: 0x6040, sub_index: 0 } # controlword
        - { index: 0x6060, sub_index: 0 } # mode of operation
    2:
      enabled: true
      cob_id: "auto"
      mapping:
        - { index: 0x607A, sub_index: 0 } # target position
        - { index: 0x6042, sub_index: 0 } # target velocity
