#!/usr/bin/env python
from os.path import join
import rospy
from power_msgs.msg import PowerStatus


paths = ["/sys/devices/3160000.i2c/i2c-0/0-0040/iio_device",
         "/sys/devices/3160000.i2c/i2c-0/0-0041/iio_device",
         "/sys/devices/3160000.i2c/i2c-0/0-0042/iio_device",
         "/sys/devices/3160000.i2c/i2c-0/0-0043/iio_device"]

objects = ["in_current",
           "in_voltage"]

msg = PowerStatus()
msg.rail = [0.0] * 12
msg.voltage = [0.0] * 12
msg.current = [0.0] * 12

index = 0
counter = 0


StatusPub = rospy.Publisher('power_status', PowerStatus, queue_size=10)
rospy.init_node('power_monitor', anonymous=True)
rate = rospy.Rate(2)
for i in range(0,12):
    railname = "rail_name_" + str(i % 3)
    msg.rail[i] = str(open(join(paths[i//3], railname), 'r').read()[:-1])
while not rospy.is_shutdown():
    for i in range(0, 12):
        CurrentName = objects[0] + str(i % 3) + "_input"
        VoltageName = objects[1] + str(i % 3) + "_input"
        msg.current[i] = float(open(join(paths[i//3], CurrentName), 'r').read()[:-1])/1000.0
        msg.voltage[i] = float(open(join(paths[i//3], VoltageName), 'r').read()[:-1])/1000.0
    StatusPub.publish(msg)
    rate.sleep()
 

