master:
  node_id: 10
  driver: "ros2_canopen::MasterDriver"
  package: canopen_master_driver
  sync_period: 20000
  heartbeat_producer: 100

nanotec3:
  node_id: 3
  dcf: "C5-E-2-09.eds"
  dcf_path: "@BUS_CONFIG_PATH@"
  driver: "nanotec_driver::NanotecDriver"
  package: "nanotec_driver"
  period: 20
  boot: true
  heartbeat_consumer: true
  enable_lazy_load: false
  sdo:
    - { index: 0x2030, sub_index: 0, value: 8 } # Pole Pair Count
    - { index: 0x2031, sub_index: 0, value: 12000 } # Max Motor Current - 12 A
    - { index: 0x203B, sub_index: 1, value: 10000 } # Motor Rated Current - 12 A
    - { index: 0x203B, sub_index: 2, value: 100 } # Maximum Duration Of Max Current - 100ms
    - { index: 0x6073, sub_index: 0, value: 1200 } # Max Current - 100% of rated current
    - { index: 0x3202, sub_index: 0, value: 0x41 } # Motor Drive Submode Select - BLDC motor (closed loop)
    - { index: 0x3212, sub_index: 4, value: 0 } # Use old motor drive parameters
    - { index: 0x3210, sub_index: 5, value: 8192 } # Flux Current Loop, Proportional Gain (closed Loop)
    - { index: 0x3210, sub_index: 6, value: 256 } # Flux Current Loop, Integral Gain (closed Loop)
    - { index: 0x3210, sub_index: 7, value: 8192 } # Torque Current Loop, Proportional Gain (closed Loop)
    - { index: 0x3210, sub_index: 8, value: 256 } # Torque Current Loop, Integral Gain (closed Loop)
    - { index: 0x3210, sub_index: 3, value: 30000 } # Velocity Loop, Proportional Gain (closed Loop)
    - { index: 0x3210, sub_index: 4, value: 5 } # Velocity Loop, Integral Gain (closed Loop)
    - { index: 0x6083, sub_index: 0, value: 10000 } # Profile Acceleration
    - { index: 0x6084, sub_index: 0, value: 10000 } # Profile Deceleration
  tpdo:
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - { index: 0x6041, sub_index: 0 } # status word
        - { index: 0x6061, sub_index: 0 } # mode of operaiton display
    2:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - { index: 0x6064, sub_index: 0 } # position actual value
        - { index: 0x606c, sub_index: 0 } # velocity actual position
  rpdo:
    1:
      enabled: true
      cob_id: "auto"
      mapping:
        - { index: 0x6040, sub_index: 0 } # controlword
        - { index: 0x6060, sub_index: 0 } # mode of operation
    2:
      enabled: true
      cob_id: "auto"
      mapping:
        - { index: 0x607A, sub_index: 0 } # target position
        - { index: 0x6042, sub_index: 0 } # target velocity
