master:
  node_id: 10
  driver: "ros2_canopen::MasterDriver"
  package: canopen_master_driver
  sync_period: 20000

nanotec3:
  node_id: 3
  dcf: "C5-E-2-09.eds"
  dcf_path: "install/share/aleph2_canopen/config/nanotec"
  driver: "aleph2_canopen::NanotecDriver"
  package: "aleph2_canopen"
  period: 20
  enable_lazy_load: false
  sdo:
    - { index: 0x2030, sub_index: 0, value: 8 } # Pole Pair Count
    - { index: 0x2031, sub_index: 0, value: 25000 } # Max Motor Current - 25 A
    - { index: 0x6075, sub_index: 0, value: 25000 } # Motor Rated Current - 25 A
    - { index: 0x6073, sub_index: 0, value: 1000 } # Max Current - 100% of rated current
    - { index: 0x203B, sub_index: 2, value: 100 } # Maximum Duration Of Max Current - 100ms
    - { index: 0x3202, sub_index: 0, value: 0x40 } # Motor Drive Submode Select - BLDC motor
    # - { index: 0x6042, sub_index: 0, value: 2 } # Velocity mode
  tpdo:
    1:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - { index: 0x6041, sub_index: 0 } # status word
        - { index: 0x6061, sub_index: 0 } # mode of operaiton display
    2:
      enabled: true
      cob_id: "auto"
      transmission: 0x01
      mapping:
        - { index: 0x6064, sub_index: 0 } # position actual value
        - { index: 0x606c, sub_index: 0 } # velocity actual position
    3:
      enabled: false
    4:
      enabled: false
  rpdo:
    1:
      enabled: true
      cob_id: "auto"
      mapping:
        - { index: 0x6040, sub_index: 0 } # controlword
        - { index: 0x6060, sub_index: 0 } # mode of operation
    2:
      enabled: true
      cob_id: "auto"
      mapping:
        - { index: 0x607A, sub_index: 0 } # target position
        - { index: 0x6042, sub_index: 0 } # target velocity
